# Generated by Django 5.0.4 on 2024-08-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_posts_community_alter_posts_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
