# Generated by Django 5.0.4 on 2024-08-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_posts_text_alter_posts_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='username',
            field=models.CharField(max_length=300),
        ),
    ]
