# Generated by Django 5.0.4 on 2024-08-31 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_posts_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
