# Generated by Django 5.0.4 on 2024-09-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_posts_username_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='parent',
            new_name='parent_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='username',
            new_name='user_id',
        ),
    ]
