# Generated by Django 5.0.4 on 2024-09-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_rename_parent_comments_parent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='user',
        ),
    ]
