# Generated by Django 5.0.4 on 2024-09-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_comments_downvotes_comments_upvotes_posts_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.BooleanField(),
        ),
    ]
