# Generated by Django 5.0.4 on 2024-09-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_vote_vote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
