# Generated by Django 5.0.4 on 2024-10-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_comments_downvotes_alter_comments_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
