# Generated by Django 5.0.4 on 2024-05-14 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='genre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='publisher',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='magazine',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
