# Generated by Django 5.0.4 on 2024-06-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_magazine_last_updated_alter_magazine_upload_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='publisher',
        ),
    ]
