# Generated by Django 5.0.4 on 2024-06-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_magazine_last_updated_alter_magazine_upload_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='magazine',
            name='document',
            field=models.FileField(upload_to='library/'),
        ),
    ]
