# Generated by Django 5.0.4 on 2024-05-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_magazine_genre_magazine_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
