# Generated by Django 5.0.4 on 2024-06-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_remove_magazine_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover/'),
        ),
    ]
