# Generated by Django 5.0.4 on 2024-05-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0004_alter_magazine_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='document',
            field=models.FileField(upload_to='library/'),
        ),
    ]
