# Generated by Django 5.0.4 on 2024-06-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0004_magazine_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='magazine',
            name='img1',
            field=models.ImageField(default='', upload_to='highlight/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='img2',
            field=models.ImageField(default='', upload_to='highlight/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='img3',
            field=models.ImageField(default='', upload_to='highlight/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='t1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='t2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='t3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='theme',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='upload_date',
            field=models.DateTimeField(null=True),
        ),
    ]
