# Generated by Django 5.0.4 on 2024-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0006_alter_magazine_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='t1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='t2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='t3',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
