# Generated by Django 5.0.4 on 2024-05-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('saved_magazines', models.JSONField()),
                ('saved_count', models.IntegerField()),
            ],
        ),
    ]
