# Generated by Django 5.0.4 on 2024-06-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_remove_magazine_last_updated_and_more'),
        ('user', '0003_alter_customuser_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='saved_users', to='magazines.magazine'),
        ),
    ]
