# Generated by Django 5.0.4 on 2024-05-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0005_alter_magazine_document'),
        ('user', '0003_alter_customuser_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='saved_users', to='magazines.magazine'),
        ),
    ]
