# Generated by Django 5.0.4 on 2024-06-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
