# Generated by Django 5.0.4 on 2024-08-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='favorites',
            new_name='magazine_favorites',
        ),
    ]
