# Generated by Django 5.0.4 on 2024-08-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_posts_username'),
        ('user', '0006_rename_favorites_customuser_magazine_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='post_favorites',
            field=models.ManyToManyField(blank=True, related_name='saved_users', to='forum.posts'),
        ),
    ]
