# Generated by Django 5.0.4 on 2024-08-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_posts_upload_date'),
        ('user', '0007_customuser_post_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='post_favorites',
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to='forum.posts'),
        ),
    ]
